"""The bundled license notice covers exactly the crates we ship.

The wheel contains compiled code from every crate in the dependency tree, and
their licenses require the copyright notice to travel with the binary.
``THIRD-PARTY-LICENSES.md`` is that notice. It is generated by
``scripts/gen_third_party_licenses.py``, and a generated file that nothing checks
drifts the first time a dependency is added -- silently, because a notice missing
one crate looks exactly like a complete one.

The comparison is against ``cargo metadata`` rather than against a re-run of
cargo-about, so the check needs only a Rust toolchain, which every CI job that
builds the extension already has. It runs in both directions: a crate we ship
without a notice is the license problem, and a notice naming a crate we dropped
is the sign the file was hand-edited.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess

import pytest

from tests.helpers import REPO_ROOT, repo_checkout_available

pytestmark = pytest.mark.skipif(
    not repo_checkout_available(),
    reason="repository files are not present (installed-wheel smoke test)",
)

NOTICE = REPO_ROOT / "THIRD-PARTY-LICENSES.md"

#: A crate entry in the rendered "Applies to" lists: ``- [name 1.2.3](url)``.
ENTRY = re.compile(r"^- \[([A-Za-z0-9_.\-]+) [^\]]+\]\(", re.MULTILINE)

#: Our own crate. Its terms are in LICENSE; the notice is about third parties.
SELF_CRATE = "xlsxturbo"

#: A dependency edge cfg'd to a predicate that is false for every target, which
#: is the idiom for "declared but never compiled anywhere". `serde_core` reaches
#: `serde_derive` this way, and cargo-about is right to omit it: no artifact we
#: ship contains a byte of it. Every other `cfg(...)` edge is kept, so a
#: Windows-only crate still gets its notice in the macOS-built wheel's file.
NEVER_COMPILED = "cfg(any())"


def _shipped_crates() -> set[str]:
    """Names of every crate compiled into what we distribute.

    Walks ``cargo metadata``'s resolved graph from the root package, following
    normal and build dependencies and refusing dev-dependency edges -- proptest
    and its tree compile only into test binaries, so their notices do not belong
    in a file about the wheel. Default features, which is what maturin builds
    with (it adds ``pyo3/extension-module`` on top).

    Returns:
        The crate names, excluding xlsxturbo itself.
    """
    raw = subprocess.run(
        ["cargo", "metadata", "--format-version", "1"],  # noqa: S607 - cargo is on PATH by design here
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    meta = json.loads(raw)
    nodes = {node["id"]: node for node in meta["resolve"]["nodes"]}
    names = {pkg["id"]: pkg["name"] for pkg in meta["packages"]}

    root = meta["resolve"]["root"]
    assert root is not None, "cargo metadata reported no root package"

    seen: set[str] = set()
    queue = [root]
    while queue:
        current = queue.pop()
        for dep in nodes[current]["deps"]:
            compiled = [
                kind
                for kind in dep["dep_kinds"]
                if kind["kind"] != "dev" and kind.get("target") != NEVER_COMPILED
            ]
            if not compiled:
                continue
            if dep["pkg"] not in seen:
                seen.add(dep["pkg"])
                queue.append(dep["pkg"])

    shipped = {names[pkg_id] for pkg_id in seen} - {SELF_CRATE}
    assert len(shipped) > 20, f"the dependency walk found only {len(shipped)} crates; it is not working"
    return shipped


def _noticed_crates() -> set[str]:
    """Crate names listed in the committed notice file.

    Returns:
        The names, which the file lists once per license that applies to them.
    """
    listed = set(ENTRY.findall(NOTICE.read_text(encoding="utf-8")))
    assert listed, "no crate entries parsed out of the notice; the pattern or the template changed"
    return listed


class TestNoticeCoversWhatWeShip:
    """The notice and the dependency graph agree, in both directions."""

    def test_the_notice_file_exists(self) -> None:
        """Absent, every other check here would vacuously pass or error oddly."""
        assert NOTICE.is_file(), "THIRD-PARTY-LICENSES.md is missing; run scripts/gen_third_party_licenses.py --write"

    @pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
    def test_every_shipped_crate_has_a_notice(self) -> None:
        """A dependency added without regenerating fails here.

        This is the direction that is a license problem rather than untidiness:
        we would be distributing a binary containing someone's code without
        their copyright notice.
        """
        missing = _shipped_crates() - _noticed_crates()
        assert not missing, (
            f"crates shipped with no license notice: {sorted(missing)} -- "
            "run `python scripts/gen_third_party_licenses.py --write`"
        )

    @pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
    def test_the_notice_names_no_crate_we_dropped(self) -> None:
        """The other direction, which catches a hand-edited or stale file.

        A notice for a crate we no longer ship is harmless to its author and
        useless to our users, but it is evidence the file stopped being
        generated -- and the first direction cannot see that.
        """
        extra = _noticed_crates() - _shipped_crates()
        assert not extra, (
            f"the notice lists crates that are not in the dependency graph: {sorted(extra)} -- "
            "run `python scripts/gen_third_party_licenses.py --write`"
        )

    def test_it_does_not_claim_to_cover_xlsxturbo_itself(self) -> None:
        """cargo-about includes the root crate; the generator drops it.

        Without this, the generator's ``_drop_self_section`` could stop working
        and nothing would notice, because a file with one extra section still
        satisfies both comparisons above.
        """
        assert SELF_CRATE not in _noticed_crates()

    def test_the_wheel_is_told_to_ship_it(self) -> None:
        """A notice nobody receives is not a notice.

        `license-files` is what puts the file into the wheel's
        `.dist-info/licenses/`, and it is PEP 639, which maturin gained in 1.9.0.
        An older backend ignores the key and builds a wheel carrying neither
        notice, with nothing going red -- so the declaration and the floor that
        makes it work are asserted together, because either alone is useless.
        """
        pyproject = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
        declared = re.search(r"^license-files = \[(.*)\]", pyproject, re.MULTILINE)
        assert declared, "pyproject.toml declares no license-files"
        assert "THIRD-PARTY-LICENSES.md" in declared.group(1)
        assert "LICENSE" in declared.group(1)

        requires = re.search(r'^requires = \["maturin>=(\d+)\.(\d+)', pyproject, re.MULTILINE)
        assert requires, "pyproject.toml declares no maturin build requirement"
        major, minor = int(requires.group(1)), int(requires.group(2))
        assert (major, minor) >= (1, 9), (
            f"maturin>={major}.{minor} predates PEP 639 support (1.9.0); "
            "the license files would be silently dropped from the wheel"
        )

    def test_the_license_texts_are_actually_present(self) -> None:
        """Names and links are not a notice -- the text is what is required.

        A template change that dropped the ``{{{text}}}`` block would leave a
        plausible-looking index of crates and satisfy every check above.
        """
        body = NOTICE.read_text(encoding="utf-8")
        assert body.count("Permission is hereby granted, free of charge") >= 10, "MIT notice texts are missing"
        assert "Apache License" in body
        assert body.count("```text") >= 20, "license texts are not being emitted"
