"""Tests for the generated capability matrix documentation page.

The page is derived from the Rust sources by `scripts/gen_capability_matrix.py`.
These tests guard the two ways that can go wrong: the committed page drifting
from the sources, and the generator's parsers silently matching nothing.
"""

from __future__ import annotations

import importlib
import subprocess
import sys
from types import ModuleType

import pytest

from tests.helpers import REPO_ROOT, repo_checkout_available

SCRIPT = REPO_ROOT / "scripts" / "gen_capability_matrix.py"
DOC = REPO_ROOT / "docs" / "capability-matrix.md"

# This module audits the generator script and its committed output, neither of
# which ships in the wheel. Outside a checkout there is nothing here to test --
# see `repo_checkout_available` for why that case is real and not theoretical.
# Inside a checkout a missing script or page is still a hard failure.
pytestmark = pytest.mark.skipif(
    not repo_checkout_available(),
    reason="capability-matrix tests audit repository files, which a wheel install does not carry",
)


def _load_generator() -> ModuleType:
    """Import the generator script as a module.

    Imports by name off `sys.path` rather than through
    `spec_from_file_location` + `spec.loader.exec_module`. The latter is a
    typeshed minefield: `ModuleSpec.loader` is typed as `Loader | None`, and
    whether `Loader` declares `exec_module` varies between typeshed versions --
    so that spelling passed pyright locally and failed it in CI.

    Returns:
        The imported module.
    """
    scripts_dir = str(SCRIPT.parent)
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    return importlib.import_module("gen_capability_matrix")


class TestCapabilityMatrixFreshness:
    """The committed page must match what the sources currently say."""

    def test_committed_page_is_current(self) -> None:
        """`--check` passes, i.e. nobody changed an option without regenerating."""
        result = subprocess.run(  # noqa: S603 - fixed argv, no shell
            [sys.executable, str(SCRIPT), "--check"],
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
        )
        assert result.returncode == 0, (
            f"docs/capability-matrix.md is out of date.\n"
            f"Run: python scripts/gen_capability_matrix.py --write\n"
            f"{result.stdout}{result.stderr}"
        )

    def test_page_exists_and_is_marked_generated(self) -> None:
        """The page carries the do-not-edit marker, so a hand edit is obvious."""
        assert DOC.exists(), "docs/capability-matrix.md is missing; run the generator with --write"
        assert "generated by scripts/gen_capability_matrix.py" in DOC.read_text(encoding="utf-8")


class TestGeneratorParsers:
    """Each parser must find a non-empty population.

    A structural audit that finds no instances of its own pattern reports nothing
    to flag, which reads exactly like a clean result. So every parser is asserted
    to return something, and the counts are pinned against the sources rather
    than against the generated page -- otherwise both sides could drift together.
    """

    def test_sheet_option_names_non_empty(self) -> None:
        """`SHEET_OPTION_NAMES` parses to a plausible number of options."""
        names = _load_generator().parse_sheet_option_names()
        assert len(names) > 10, f"expected many per-sheet options, parsed {len(names)}: {names}"
        assert "column_widths" in names
        assert "cells" in names

    def test_complex_options_non_empty(self) -> None:
        """`define_options!` parses to its field list."""
        fields = _load_generator().parse_complex_options()
        assert len(fields) > 10, f"expected many complex options, parsed {len(fields)}: {fields}"
        assert "charts" in fields

    def test_constant_memory_safe_is_small_and_specific(self) -> None:
        """The safe list is short by design; a surprise addition should be noticed."""
        safe = _load_generator().parse_constant_memory_safe()
        assert safe, "CONSTANT_MEMORY_SAFE_OPTIONS parsed to zero entries"
        assert len(safe) <= 5, (
            f"the constant_memory safe list grew to {len(safe)} ({safe}). That is allowed, but it "
            "should be a deliberate decision -- update this bound if so."
        )

    def test_constant_memory_disabled_scalars_non_empty(self) -> None:
        """The hand-listed scalar flags parse out of the warning function."""
        scalars = _load_generator().parse_constant_memory_disabled_scalars()
        assert "table_style" in scalars
        assert "freeze_panes" in scalars

    @pytest.mark.parametrize("function", ["df_to_xlsx", "dfs_to_xlsx", "csv_to_xlsx"])
    def test_signature_params_are_identifiers(self, function: str) -> None:
        """Every parsed parameter is an identifier.

        The first version of this parser spanned from the file's first pyo3
        attribute through to the requested function, producing "parameters" such
        as `) -> PyResult<(u32`. Identifiers are the cheap invariant that catches
        a misparse before it reaches the documentation looking plausible.
        """
        params = _load_generator().parse_signature_params(function)
        assert params, f"{function} parsed to zero parameters"
        for name in params:
            assert name.isidentifier(), f"{function}: {name!r} is not an identifier"

    def test_entry_points_differ_as_expected(self) -> None:
        """The three entry points have genuinely different surfaces.

        If a refactor accidentally made the parser return the same list for all
        three, every column of the matrix would agree and the table would look
        tidy while saying nothing.
        """
        gen = _load_generator()
        df = set(gen.parse_signature_params("df_to_xlsx"))
        dfs = set(gen.parse_signature_params("dfs_to_xlsx"))
        csv = set(gen.parse_signature_params("csv_to_xlsx"))

        assert "df" in df, "df_to_xlsx takes a `df` argument"
        assert "sheets" in dfs, "dfs_to_xlsx takes a `sheets` argument, not `df`"
        assert "sheet_name" in df, "df_to_xlsx names its single sheet"
        assert "sheet_name" not in dfs, "dfs_to_xlsx names sheets per tuple, not globally"
        assert len(csv) < len(df), "csv_to_xlsx should have a much smaller surface than df_to_xlsx"
        assert not (df & csv) - {"sheet_name", "output_path"}, (
            "csv_to_xlsx unexpectedly shares feature options with df_to_xlsx"
        )
