"""Generate the capability matrix documentation page from the Rust sources.

Which options work in which mode is decided in four places in `src/`, and a
hand-maintained table drifts from them the first time a feature is added. This
script derives the table instead:

* `SHEET_OPTION_NAMES` (`src/extract.rs`) -- options overridable per sheet.
* `define_options!` (`src/types.rs`) -- the "complex" feature options.
* `CONSTANT_MEMORY_SAFE_OPTIONS` and `warn_constant_memory_skips`
  (`src/convert.rs`) -- what survives `constant_memory=True`.
* The `#[pyo3(signature = ...)]` blocks (`src/lib.rs`) -- what each entry point
  actually accepts.

Run with no arguments to print the page, `--write` to update it in place, or
`--check` to verify the committed page is current (which is what the test does).

Every parser here raises on an empty result. A structural audit that finds no
instances of its own pattern reports "nothing to flag", which is indistinguishable
from a clean result -- so a zero count is treated as a broken parse, never as an
answer.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOC_PATH = REPO_ROOT / "docs" / "capability-matrix.md"

#: Entry points whose signatures are documented, in presentation order.
ENTRY_POINTS = ("df_to_xlsx", "dfs_to_xlsx", "csv_to_xlsx")

#: Parameters that carry data or a destination rather than configuring output.
#: Excluded from the matrix because "does df_to_xlsx accept df" is not a
#: capability question.
NON_OPTION_PARAMS = frozenset({"df", "dfs", "sheets", "input_path", "output_path"})

GENERATED_MARKER = "<!-- generated by scripts/gen_capability_matrix.py -- do not edit by hand -->"


class ParseError(RuntimeError):
    """A source pattern this script depends on produced no matches."""


def _read(relative: str) -> str:
    """Read a repository file as text.

    Args:
        relative: Path relative to the repository root.

    Returns:
        The file contents.
    """
    return (REPO_ROOT / relative).read_text(encoding="utf-8")


def _parse_str_slice(source: str, const_name: str, origin: str) -> list[str]:
    """Extract the string literals from a Rust `&[&str]` constant.

    Args:
        source: Rust source text to search.
        const_name: Name of the constant to read.
        origin: File name, used in the error message.

    Returns:
        The string literals in declaration order.

    Raises:
        ParseError: If the constant is absent or holds no literals.
    """
    match = re.search(
        rf"const\s+{re.escape(const_name)}\s*:\s*&\[&str\]\s*=\s*&\[(.*?)\];",
        source,
        re.DOTALL,
    )
    if match is None:
        raise ParseError(f"{origin}: could not locate `const {const_name}: &[&str]`")
    names = re.findall(r'"([^"]+)"', match.group(1))
    if not names:
        raise ParseError(f"{origin}: `{const_name}` parsed to zero entries")
    return names


def parse_sheet_option_names() -> list[str]:
    """Read the per-sheet-overridable option names.

    Returns:
        Option names in declaration order.
    """
    return _parse_str_slice(_read("src/extract.rs"), "SHEET_OPTION_NAMES", "src/extract.rs")


def parse_constant_memory_safe() -> list[str]:
    """Read the options that still apply under `constant_memory=True`.

    Returns:
        Option names in declaration order.
    """
    return _parse_str_slice(_read("src/convert.rs"), "CONSTANT_MEMORY_SAFE_OPTIONS", "src/convert.rs")


def parse_complex_options() -> list[str]:
    """Read the `define_options!` field names.

    These are the options extracted into typed Rust structures, as opposed to the
    scalar flags carried on `WriteConfig`.

    Returns:
        Field names in declaration order.

    Raises:
        ParseError: If the macro invocation is absent or holds no fields.
    """
    source = _read("src/types.rs")
    match = re.search(r"^define_options!\s*\{(.*?)^\}", source, re.DOTALL | re.MULTILINE)
    if match is None:
        raise ParseError("src/types.rs: could not locate the `define_options!` invocation")
    fields = re.findall(r"^\s{4}(\w+)\s*:", match.group(1), re.MULTILINE)
    if not fields:
        raise ParseError("src/types.rs: `define_options!` parsed to zero fields")
    return fields


def parse_constant_memory_disabled_scalars() -> list[str]:
    """Read the scalar flags that `constant_memory=True` disables.

    Only the hand-listed scalar flags are returned; the complex options are
    derived from `CONSTANT_MEMORY_SAFE_OPTIONS` instead, because the Rust side
    generates those from the option fields rather than listing them.

    Returns:
        Flag names in the order they are checked.

    Raises:
        ParseError: If the warning function is absent or pushes no scalar names.
    """
    source = _read("src/convert.rs")
    match = re.search(
        r"fn warn_constant_memory_skips\b.*?\n\}",
        source,
        re.DOTALL,
    )
    if match is None:
        raise ParseError("src/convert.rs: could not locate `fn warn_constant_memory_skips`")
    names = re.findall(r'disabled\.push\("([^"]+)"\)', match.group(0))
    if not names:
        raise ParseError("src/convert.rs: `warn_constant_memory_skips` pushes zero literal names")
    return names


def parse_signature_params(function: str) -> list[str]:
    """Read the Python-visible parameter names of one entry point.

    Args:
        function: The Rust function name, e.g. `df_to_xlsx`.

    Returns:
        Parameter names in signature order.

    Raises:
        ParseError: If the function's `#[pyo3(signature = ...)]` block is absent
            or holds no parameters.
    """
    source = _read("src/lib.rs")

    # Locate each attribute by its own delimiters rather than with one regex
    # spanning to `fn <name>`. A non-greedy `.*?` between the two still matched
    # from the FIRST signature in the file through to the requested function,
    # swallowing every function body in between and yielding "parameters" like
    # `) -> PyResult<(u32`. The attribute ends at `))]`, so use that.
    for opening in re.finditer(r"#\[pyo3\(signature\s*=\s*\(", source):
        start = opening.end()
        end = source.find("))]", start)
        if end == -1:
            continue
        following = re.search(r"fn\s+(\w+)", source[end:])
        if following is None or following.group(1) != function:
            continue

        params: list[str] = []
        for raw in source[start:end].split(","):
            name = raw.split("=")[0].strip()
            if not name:
                continue
            # A parameter name is an identifier. Anything else means the block
            # boundaries were misread, and a wrong answer here would propagate
            # into the documentation looking plausible.
            if not name.isidentifier():
                raise ParseError(
                    f"src/lib.rs: signature for `{function}` yielded {name!r}, which is not an identifier -- "
                    "the attribute boundaries were misparsed"
                )
            params.append(name)

        if not params:
            raise ParseError(f"src/lib.rs: signature for `{function}` parsed to zero parameters")
        return params

    raise ParseError(f"src/lib.rs: could not locate a pyo3 signature for `{function}`")


def _mode_cell(option: str, params: Sequence[str]) -> str:
    """Render whether one option is accepted by one entry point.

    Args:
        option: Option name.
        params: That entry point's parameter names.

    Returns:
        A markdown cell.
    """
    return "yes" if option in params else "--"


def build_matrix() -> str:
    """Build the capability matrix page.

    Returns:
        The full markdown document.
    """
    sheet_options = parse_sheet_option_names()
    complex_options = parse_complex_options()
    cm_safe = parse_constant_memory_safe()
    cm_disabled_scalars = parse_constant_memory_disabled_scalars()

    signatures: dict[str, list[str]] = {fn: parse_signature_params(fn) for fn in ENTRY_POINTS}

    # Every option any entry point accepts, in the order df_to_xlsx declares
    # them, then anything only another entry point has.
    ordered: list[str] = []
    for fn in ENTRY_POINTS:
        for param in signatures[fn]:
            if param not in NON_OPTION_PARAMS and param not in ordered:
                ordered.append(param)

    per_sheet: set[str] = set(sheet_options)
    # A complex option not on the safe list is skipped under constant_memory;
    # the Rust side derives that from the generated field list, so the same
    # subtraction is done here rather than re-listing it.
    cm_disabled: set[str] = set(cm_disabled_scalars) | (set(complex_options) - set(cm_safe))

    lines: list[str] = [
        "# Capability matrix",
        "",
        GENERATED_MARKER,
        "",
        "Which option applies in which mode. Generated from the Rust sources, so it cannot",
        "drift from the implementation -- see `scripts/gen_capability_matrix.py`.",
        "",
        "- **df_to_xlsx** / **dfs_to_xlsx** / **csv_to_xlsx** -- whether the entry point accepts the option.",
        "- **Per sheet** -- whether `dfs_to_xlsx` lets a sheet override it, as opposed to only",
        "  accepting it as a workbook-wide default.",
        "- **constant_memory** -- whether it still applies when `constant_memory=True`. Options",
        "  marked `skipped` are ignored with a `RuntimeWarning` naming them. `applies (inert)`",
        "  means it is applied but has no observable effect, because what it configures is",
        "  itself skipped.",
        "",
        "| Option | df_to_xlsx | dfs_to_xlsx | csv_to_xlsx | Per sheet | constant_memory |",
        "|---|---|---|---|---|---|",
    ]

    for option in ordered:
        if option == "constant_memory":
            # The switch itself is not one of the things it switches off.
            cm = "n/a"
        elif option in cm_disabled:
            cm = "skipped"
        elif option == "table_name":
            # Accepted and applied, but it names an Excel table that only exists
            # when `table_style` is set -- and that is skipped here, so in
            # practice it has nothing to name.
            cm = "applies (inert)"
        else:
            cm = "applies"
        lines.append(
            f"| `{option}` "
            f"| {_mode_cell(option, signatures['df_to_xlsx'])} "
            f"| {_mode_cell(option, signatures['dfs_to_xlsx'])} "
            f"| {_mode_cell(option, signatures['csv_to_xlsx'])} "
            f"| {'yes' if option in per_sheet else '--'} "
            f"| {cm} |"
        )

    csv_only = [p for p in signatures["csv_to_xlsx"] if p not in NON_OPTION_PARAMS]
    lines += [
        "",
        "## What the shape of this table says",
        "",
        f"`csv_to_xlsx` takes {len(csv_only)} options ({', '.join(f'`{p}`' for p in csv_only)}) and none of the",
        "formatting or feature options. CSV conversion is a straight-through fast path, not a",
        "reduced-feature version of the DataFrame path: to format a CSV export, read it into a",
        "DataFrame and use `df_to_xlsx`.",
        "",
        f"`constant_memory=True` keeps {len(cm_safe)} of the feature options "
        f"({', '.join(f'`{o}`' for o in cm_safe)}) and skips",
        f"{len(cm_disabled)}. Those three are the ones applied while rows are being written; everything",
        "else needs to revisit a cell after the fact, which streaming output cannot do. A new",
        "option defaults to skipped, so this list only grows deliberately.",
        "",
        f"Of the {len(ordered)} options, {len(per_sheet)} can be overridden per sheet in `dfs_to_xlsx`. The rest are",
        "workbook-wide.",
        "",
    ]
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point.

    Args:
        argv: Command-line arguments, defaulting to `sys.argv[1:]`.

    Returns:
        Process exit status.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="update the documentation page in place")
    parser.add_argument("--check", action="store_true", help="fail if the committed page is out of date")
    args = parser.parse_args(argv)

    generated = build_matrix()

    if args.check:
        if not DOC_PATH.exists():
            print(f"[FAIL] {DOC_PATH.relative_to(REPO_ROOT)} does not exist; run with --write")
            return 1
        current = DOC_PATH.read_text(encoding="utf-8")
        if current != generated:
            print(f"[FAIL] {DOC_PATH.relative_to(REPO_ROOT)} is out of date; run with --write")
            return 1
        print(f"[OK] {DOC_PATH.relative_to(REPO_ROOT)} is current")
        return 0

    if args.write:
        DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" explicitly: the default would write CRLF on Windows, and
        # while --check survives that (read_text translates universal newlines
        # back to \n), the committed bytes would then depend on which platform
        # ran the generator.
        DOC_PATH.write_text(generated, encoding="utf-8", newline="\n")
        print(f"[OK] wrote {DOC_PATH.relative_to(REPO_ROOT)}")
        return 0

    print(generated)
    return 0


if __name__ == "__main__":
    sys.exit(main())
